### ISSUE TITLE
Provider.request response not fit origin provider.send response

### ISSUE THREAD

**Issue by aiden-cao** [wallet-guard/wallet-guard-extension#110]
https://github.com/wallet-guard/wallet-guard-extension/blob/221ad3eb329ad7681b16a37c7ddfaf173dba6e7f/src/injected/injectWalletGuard.tsx#L49-L62

The plugin will break down the existing functionality of the website.

**Comment by mindofmar** [comment]
@aiden-cao Could you share the website you're experiencing issues with?
